# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/saycan',
                'doc_host': 'https://xrsrke.github.io',
                'git_url': 'https://github.com/xrsrke/saycan',
                'lib_path': 'saycan'},
  'syms': {'saycan.core': {'saycan.core.foo': ('core.html#foo', 'saycan/core.py')}, 'saycan.env': {}}}
